watcherfield.type.name=Watcher Field
watcherfield.type.desc=Used for modifying watchers on issue creation/update.

watcherfield.searcher.name=Watcher Searcher
watcherfield.searcher.desc=Used to search for watchers on issues.

watcherfield.nopermission.body=You do not have permission to manage the watcher list.

watcherfield.section.label=Watchers Custom Field

watcherfield.settings.name=Watcher Field Settings
watcherfield.settings.desc=The settings for the watcher field plugin

watcherfield.settings.item.ignorePermissions.name=Allow JIRA to add watchers independently
watcherfield.settings.item.ignorePermissions.desc=This settings allows JIRA to add watchers using the watcher field without using a user account (null user).  Useful when adding default watchers when creating issue via email.<br/><b>Warning:</b> This ignores the "Manage Watcher" permissions.
watcherfield.settings.item.ignorePermissions.warning=Warning: This setting circumvents the JIRA Manage Watcher permission. Only set this if you absolutely need to.

watcherfield.settings.edit.title=Edit Settings
watcherfield.settings.edit.link=Edit Configuration

watcherfield.settings.link.name=Watcher Field Settings Link
watcherfield.settings.link.label=Watcher Field Settings
watcherfield.settings.link.desc=Link to the watcher field plugin settings