watcherfield.type.name=Watcher Field
watcherfield.type.desc=Used for modifying watchers on issue creation/update.

watcherfield.searcher.name=Watcher Searcher
watcherfield.searcher.desc=Used to search for watchers on issues.

watcherfield.manager.name=Watcher Manager Reindexer
watcherfield.manager.desc=Reindexes the issue when a watcher is added.

watcherfield.js.name=Watcher Field Javascript
watcherfield.js.desc=Javascript used by the Watcher Field.

watcherfield.rest.name=Watcher REST
watcherfield.rest.desc=Interface to access the watcher information via REST.

watcherfield.nopermission.body=You do not have permission to manage the watcher list.

watcherfield.settings.name=Watcher Field Settings
watcherfield.settings.desc=The settings for the watcher field plugin

watcherfield.settings.item.ignorePermissions.name=Allow JIRA to add watchers independently
watcherfield.settings.item.ignorePermissions.desc=This settings allows JIRA to add watchers using the watcher field without using a user account (null user).  Useful when adding default watchers when creating issue via email.<br/><b>Warning:</b> This ignores the "Manage Watcher" permissions.

watcherfield.settings.link.name=Watcher Field Settings Link
watcherfield.settings.link.label=Watcher Field Settings
watcherfield.settings.link.desc=Link to the for the watcher field plugin settings