watcherfield.type.name=Watcher Field
watcherfield.type.desc=Used for modifying watchers on issue creation/update.

watcherfield.searcher.name=Watcher Searcher
watcherfield.searcher.desc=Used to search for watchers on issues.

watcherfield.nopermission.body=You do not have permission to manage the watcher list.